### ISSUE TITLE
Windows error about SR module

### ISSUE THREAD

**Issue by HenryKang1** [Meta-Portrait/MetaPortrait#19]
Error message.
Since I do not have multi gpu, My command was 
python Experimental_root/test.py -opt options/test/same_id_demo.yml 
Follow the same folder structure in the Readme.

```
Traceback (most recent call last):
  File "Experimental_root/test.py", line 21, in <module>
    test_pipeline(root_path)
  File "d:\sad_talker\metaportrait-main\sr_model\basicsr\basicsr\test.py", line 40, in test_pipeline
    model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
  File "d:\sad_talker\metaportrait-main\sr_model\basicsr\basicsr\models\base_model.py", line 48, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "d:\sad_talker\metaportrait-main\sr_model\basicsr\basicsr\models\video_base_model.py", line 116, in nondist_validation
    self.dist_validation(dataloader, current_iter, tb_logger, save_img)
  File "D:\sad_talker\MetaPortrait-main\sr_model\Experimental_root\models\metaportrait_video_model.py", line 263, in dist_validation
    concat_frame_list = folder_to_concat_folder(folder_list)
  File "d:\sad_talker\metaportrait-main\sr_model\basicsr\basicsr\utils\img_util.py", line 162, in folder_to_concat_folder
    assert len(image_name_dict[order_image[0]])>0, f"number of frames at {f} should be large than zero"
AssertionError: number of frames at D:\sad_talker\MetaPortrait-main\sr_model\results\temporal_gfpgan_same_id_temporal_super_resolution\visualization\00000000\hdtf_random should be large than zero
```
Any idear that I should change somewhere in the path?

**Comment by xiao-keeplearning** [comment]
same question. Have you solved?

**Comment by Rey405537** [comment]
same question
do you fix it?
