### ISSUE TITLE
Problems when running Temporal Super-resolution Model

### ISSUE THREAD

**Issue by xueziii** [Meta-Portrait/MetaPortrait#23]
When I try to execute the example commands in the Temporal Super-resolution Model section, I get the following error:

Traceback (most recent call last):
  File "Experimental_root/test.py", line 21, in <module>
    test_pipeline(root_path)
  File "/home/adminroot/anaconda3/lib/python3.8/site-packages/basicsr/test.py", line 28, in test_pipeline
    test_set = build_dataset(dataset_opt)
  File "/home/adminroot/anaconda3/lib/python3.8/site-packages/basicsr/data/__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "/home/adminroot/Desktop/xue/MetaPortrait-main/sr_model/Experimental_root/dataset/metaportrait_video_dataset.py", line 32, in __init__
    super(MetaportraitVideoRecurrentTestDataset, self).__init__(opt)
  File "/home/adminroot/anaconda3/lib/python3.8/site-packages/basicsr/data/video_test_dataset.py", line 99, in __init__
    raise ValueError(f'Non-supported video test dataset: {type(opt["name"])}')
ValueError: Non-supported video test dataset: <class 'str'>

How can I solve it? Thanks!

**Comment by angussiu260** [comment]
I got the same problem. Please help

**Comment by xueziii** [comment]
I have solved this problem, don't install basicsr with pip, it is wrong to install the official basicsr. Uninstall it if you have it installed. Let the code import the basicsr in the sr_model file given by the author

@angussiu260
